//
//  GithubModels.swift
//  GIthubListClean
//
//  Created by A667243 A667243 on 30/8/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Github
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
        var pageNumber: Int
        var githubUser: [GitHubUser]?
        var updateAt: Int = 0
    }
    struct Response
    {
        var dataArray: [Sunset]?
        var githubUser: [GitHubUser]?
        var updateAt: Int = 0
    }
    struct ViewModel
    {
        var dataArray: [Sunset]?
        var githubUser: [GitHubUser]?
        var updateAt: Int = 0
    }
  }
}

struct Sunset: Codable {
    let title: String
    let imageName: String
}

struct GitHubUser: Codable {
    var login: String?
    var id: Int?
    var nodeId: String?
    var avatarUrl: String?
    var gravatarId: String?
    var url: String?
    var htmlUrl: String?
    var followersUrl: String?
    var followingUrl: String?
    var gistsUrl: String?
    var starredUrl: String?
    var subscriptionsUrl: String?
    var organizationsUrl: String?
    var reposUrl: String?
    var eventsUrl: String?
    var receivedEventsUrl: String?
    var type: String?
    var siteAdmin: Bool?
    var liked: Bool = false
    
    enum CodingKeys: String, CodingKey {
        case login = "login"
        case avatarUrl = "avatar_url"
        case url = "url"
    }
}
