//
//  GithubWorker.swift
//  GIthubListClean
//
//  Created by A667243 A667243 on 30/8/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

//https://api.github.com/users

class GithubWorker {
    func doSomeWork(completionHandler: @escaping ([GitHubUser]?) -> Void) {
        // Make an API call
        let url = URL(string: "https://api.github.com/users")!
        let request = URLRequest(url: url)
        
        // Send the request
        URLSession.shared.dataTask(with: request) { data, response, error in
            if let data = data {
                let users = try? JSONDecoder().decode([GitHubUser].self, from: data)
                completionHandler(users)
            } else {
                completionHandler(nil)
            }
        }.resume()
    }
}
