//
//  GithubModels.swift
//  GIthubListClean
//
//  Created by A667243 A667243 on 30/8/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Github {
    enum UserDetail {
        struct Request {}
        struct Response {
            let githubUser: [GitHubUser]?
            let isError: Bool
            let errorMessage: String
        }
        struct ViewModel {
            let githubUser: [GitHubUser]?
        }
    }
    
    enum UserPage {
        struct Request {
            let pageNumber: Int
        }
        struct Response {
            let pageNumber: Int
        }
        struct ViewModel {
            let pageNumber: Int
        }
    }
    
    enum UserIsLiked {
        struct Request {
            let updateAt: Int
        }
        struct Response {
            let updateAt: Int
        }
        struct ViewModel {
            let updateAt: Int
        }
    }
    
}

struct GitHubUser: Codable {
    var login: String?
    var id: Int?
    var nodeId: String?
    var avatarUrl: String?
    var gravatarId: String?
    var url: String?
    var htmlUrl: String?
    var followersUrl: String?
    var followingUrl: String?
    var gistsUrl: String?
    var starredUrl: String?
    var subscriptionsUrl: String?
    var organizationsUrl: String?
    var reposUrl: String?
    var eventsUrl: String?
    var receivedEventsUrl: String?
    var type: String?
    var siteAdmin: Bool?
    var isLiked: Bool = false
    
    enum CodingKeys: String, CodingKey {
        case login = "login"
        case avatarUrl = "avatar_url"
        case url = "url"
    }
}
