//
//  GithubPresenter.swift
//  GIthubListClean
//
//  Created by A667243 A667243 on 30/8/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GithubPresentationLogic
{
  func presentSomething(response: Github.Something.Response)
    func presentGithubUser(response: Github.Something.Response)
}

class GithubPresenter: GithubPresentationLogic {
    
    weak var viewController: GithubDisplayLogic?
    
  // MARK: Do something
  
  func presentSomething(response: Github.Something.Response) {
      let data = response.dataArray
      let viewModel = Github.Something.ViewModel(
        dataArray: data
      )
    viewController?.displaySomething(viewModel: viewModel)
  }
    
    func presentGithubUser(response: Github.Something.Response) {
        let data = response.githubUser
        let viewModel = Github.Something.ViewModel(
            githubUser: data
        )
        viewController?.displayGithubUser(viewModel: viewModel)
    }
}
