//
//  GithubPresenter.swift
//  GIthubListClean
//
//  Created by A667243 A667243 on 30/8/2566 BE.
//  Copyright (c) 2566 BE ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GithubPresentationLogic {
    func presentGithubUser(response: Github.UserDetail.Response)
    func presentRefreshTable(response: Github.UserIsLiked.Response)
    func presentError(response: Github.UserDetail.Response)
}

class GithubPresenter: GithubPresentationLogic {
    
    weak var viewController: GithubDisplayLogic?
    
    func presentGithubUser(response: Github.UserDetail.Response) {
        let data = response.githubUser
        let viewModel = Github.UserDetail.ViewModel(
            githubUser: data
        )
        viewController?.displayGithubUser(viewModel: viewModel)
    }
    
    func presentRefreshTable(response: Github.UserIsLiked.Response) {
        let viewModel = Github.UserIsLiked.ViewModel(
            updateAt: response.updateAt
        )
        viewController?.refreshTable(viewModel: viewModel)
    }
    
    func presentError(response: Github.UserDetail.Response) {
        viewController?.showAlert(title: "No data", message: response.errorMessage)
    }
}
